#!/usr/bin/env bash
set -euo pipefail

cd /home/ubuntu/urban-nest-store

rm -rf client server shared patches components.json vite.config.ts tsconfig.node.json
mkdir -p src/app/catalog src/app/product/[id] src/app/wishlist src/app/cart src/app/about src/app/contacts src/app/providers src/app/store/slices
mkdir -p src/views/home src/views/catalog src/views/product src/views/wishlist src/views/cart src/views/about src/views/contacts
mkdir -p src/shared/api src/shared/config src/shared/lib src/shared/styles src/shared/ui
mkdir -p src/entities/product/model src/entities/product/ui src/entities/cart/model
mkdir -p src/features/add-to-cart/ui src/features/toggle-wishlist/ui src/features/filters/ui src/features/search-products/ui src/features/sort-products/ui src/features/change-quantity/ui
mkdir -p src/widgets/Header src/widgets/Footer src/widgets/Hero src/widgets/CatalogGrid src/widgets/CartSummary src/widgets/RelatedProducts src/widgets/Newsletter src/widgets/CategoryStrip src/widgets/Benefits

cat <<'EOF' > package.json
{
  "name": "urban-nest-store",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "eslint .",
    "typecheck": "tsc --noEmit",
    "format": "prettier --write ."
  },
  "dependencies": {
    "@reduxjs/toolkit": "^2.9.0",
    "next": "^16.0.0",
    "react": "^19.2.0",
    "react-dom": "^19.2.0",
    "react-redux": "^9.2.0",
    "styled-components": "^6.1.19"
  },
  "devDependencies": {
    "@types/node": "^24.7.0",
    "@types/react": "^19.2.1",
    "@types/react-dom": "^19.2.1",
    "@types/styled-components": "^5.1.36",
    "eslint": "^9.37.0",
    "eslint-config-next": "^16.0.0",
    "eslint-config-prettier": "^10.1.8",
    "eslint-plugin-prettier": "^5.5.5",
    "prettier": "^3.6.2",
    "typescript": "^5.9.3"
  },
  "packageManager": "pnpm@10.4.1"
}
EOF

cat <<'EOF' > next.config.mjs
/** Design reminder: Warm Scandinavian digital showroom — calm premium layouts, tactile depth, editorial spacing. */
const nextConfig = {
  compiler: {
    styledComponents: true,
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**',
      },
    ],
  },
};

export default nextConfig;
EOF

cat <<'EOF' > tsconfig.json
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF

cat <<'EOF' > next-env.d.ts
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js and should not be edited manually.
EOF

cat <<'EOF' > .eslintrc.json
{
  "extends": ["next/core-web-vitals", "next/typescript", "plugin:prettier/recommended"],
  "rules": {
    "prettier/prettier": "warn",
    "react/no-unescaped-entities": "off"
  }
}
EOF

cat <<'EOF' > .prettierrc
{
  "semi": true,
  "singleQuote": true,
  "trailingComma": "all",
  "printWidth": 100
}
EOF

cat <<'EOF' > README.md
# Urban Nest Store

Urban Nest Store is a multi-page e-commerce frontend built with **Next.js**, **TypeScript**, **styled-components**, and **Redux Toolkit**. The project follows a portfolio-oriented architecture with reusable UI primitives, domain entities, feature modules, and route-level pages.

## Stack

| Layer | Technology |
| --- | --- |
| Framework | Next.js App Router |
| UI | React 19 |
| Language | TypeScript (strict) |
| Styling | styled-components |
| State | Redux Toolkit + createAsyncThunk |
| Data | DummyJSON Products API |
| Persistence | localStorage for cart, wishlist, and catalog preferences |

## Scripts

| Command | Purpose |
| --- | --- |
| `pnpm dev` | Start the development server |
| `pnpm build` | Create production build |
| `pnpm start` | Run production server |
| `pnpm lint` | Run ESLint |
| `pnpm typecheck` | Check strict TypeScript types |
| `pnpm format` | Format project with Prettier |

## Project Structure

```text
src/
  app/
    providers/
    store/
    catalog/
    product/[id]/
    wishlist/
    cart/
    about/
    contacts/
  entities/
  features/
  shared/
  views/
  widgets/
```

## Features

The storefront includes a premium landing page, catalog with search and filtering, configurable pagination, dynamic product details with related products, wishlist, cart with quantity controls and totals, persisted UX state, static about and contacts pages, loading placeholders, empty states, and SEO-ready metadata.
EOF

cat <<'EOF' > src/shared/styles/styled.d.ts
import 'styled-components';

declare module 'styled-components' {
  export interface DefaultTheme {
    colors: {
      background: string;
      surface: string;
      surfaceAlt: string;
      text: string;
      textMuted: string;
      accent: string;
      accentSoft: string;
      border: string;
      success: string;
      danger: string;
      shadow: string;
      overlay: string;
    };
    radii: {
      sm: string;
      md: string;
      lg: string;
      pill: string;
    };
    spacing: {
      xs: string;
      sm: string;
      md: string;
      lg: string;
      xl: string;
      xxl: string;
    };
    breakpoints: {
      sm: string;
      md: string;
      lg: string;
      xl: string;
    };
    shadows: {
      card: string;
      soft: string;
      lifted: string;
    };
    fonts: {
      body: string;
      display: string;
    };
  }
}
EOF

cat <<'EOF' > src/shared/styles/theme.ts
/** Design reminder: Warm Scandinavian digital showroom — soft cream surfaces, muted sage accents, editorial whitespace. */
export const theme = {
  colors: {
    background: '#f6f0e7',
    surface: '#fffaf4',
    surfaceAlt: '#ebe4d8',
    text: '#201a17',
    textMuted: '#6d6259',
    accent: '#556b5d',
    accentSoft: '#dde6dc',
    border: 'rgba(32, 26, 23, 0.12)',
    success: '#527a5f',
    danger: '#b85b4f',
    shadow: 'rgba(53, 42, 35, 0.16)',
    overlay: 'rgba(19, 17, 15, 0.45)',
  },
  radii: {
    sm: '12px',
    md: '20px',
    lg: '32px',
    pill: '999px',
  },
  spacing: {
    xs: '0.5rem',
    sm: '0.75rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2.5rem',
    xxl: '4rem',
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
  },
  shadows: {
    card: '0 18px 40px rgba(72, 57, 47, 0.08)',
    soft: '0 8px 24px rgba(72, 57, 47, 0.06)',
    lifted: '0 30px 80px rgba(72, 57, 47, 0.14)',
  },
  fonts: {
    body: 'var(--font-body), system-ui, sans-serif',
    display: 'var(--font-display), Georgia, serif',
  },
} as const;
EOF

cat <<'EOF' > src/shared/styles/global-styles.ts
'use client';

/** Design reminder: Global styles must preserve airy spacing, quiet luxury contrast, and tactile surfaces. */
import { createGlobalStyle } from 'styled-components';

export const GlobalStyles = createGlobalStyle`
  :root {
    color-scheme: light;
  }

  * {
    box-sizing: border-box;
  }

  html {
    scroll-behavior: smooth;
  }

  body {
    margin: 0;
    background:
      radial-gradient(circle at top left, rgba(255,255,255,0.72), transparent 28%),
      linear-gradient(180deg, #f8f2ea 0%, #f1eadf 100%);
    color: ${({ theme }) => theme.colors.text};
    font-family: ${({ theme }) => theme.fonts.body};
    text-rendering: optimizeLegibility;
    min-height: 100vh;
  }

  body::before {
    content: '';
    position: fixed;
    inset: 0;
    pointer-events: none;
    opacity: 0.08;
    background-image:
      linear-gradient(rgba(32, 26, 23, 0.03) 1px, transparent 1px),
      linear-gradient(90deg, rgba(32, 26, 23, 0.03) 1px, transparent 1px);
    background-size: 100px 100px;
    z-index: -1;
  }

  a {
    color: inherit;
    text-decoration: none;
  }

  img {
    display: block;
    max-width: 100%;
    height: auto;
  }

  button,
  input,
  textarea,
  select {
    font: inherit;
  }

  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    font-family: ${({ theme }) => theme.fonts.display};
    margin: 0;
    letter-spacing: -0.03em;
  }

  p {
    margin: 0;
    line-height: 1.7;
  }
`;
EOF

cat <<'EOF' > src/app/globals.css
/* Design reminder: this file should stay quiet and structural; the visual personality lives in styled-components. */
html, body {
  padding: 0;
  margin: 0;
}
EOF

cat <<'EOF' > src/shared/config/constants.ts
/** Design reminder: product browsing should feel curated and configurable, not rigid. */
export const API_BASE_URL = 'https://dummyjson.com';
export const DEFAULT_PAGE_SIZE = 12;
export const PAGE_SIZE_OPTIONS = [6, 12, 24];
export const FEATURED_CATEGORY_SLUGS = ['furniture', 'home-decoration', 'kitchen-accessories'];
export const HERO_IMAGE =
  'https://d2xsxph8kpxj0f.cloudfront.net/310519663168568542/J7sVFfjNTLPg9JV5eBSGKb/urban-nest-hero-living-room-X5hxUF6nWjxE7rC7GMDZZF.webp';
export const CATEGORY_IMAGE =
  'https://d2xsxph8kpxj0f.cloudfront.net/310519663168568542/J7sVFfjNTLPg9JV5eBSGKb/urban-nest-category-dining-4nvWKUxtFWdCskAZouznsW.webp';
export const STORY_IMAGE =
  'https://d2xsxph8kpxj0f.cloudfront.net/310519663168568542/J7sVFfjNTLPg9JV5eBSGKb/urban-nest-brand-story-studio-8ELwYARLWG6uHqX3r2g7SR.webp';
export const NAV_LINKS = [
  { label: 'Главная', href: '/' },
  { label: 'Каталог', href: '/catalog' },
  { label: 'О нас', href: '/about' },
  { label: 'Контакты', href: '/contacts' },
  { label: 'Wishlist', href: '/wishlist' },
  { label: 'Корзина', href: '/cart' },
] as const;
EOF

cat <<'EOF' > src/shared/config/routes.ts
/** Design reminder: navigation should feel effortless and spacious, with clear escape routes from every page. */
export const routes = {
  home: '/',
  catalog: '/catalog',
  about: '/about',
  contacts: '/contacts',
  wishlist: '/wishlist',
  cart: '/cart',
  product: (id: number | string) => `/product/${id}`,
};
EOF

cat <<'EOF' > src/shared/lib/formatPrice.ts
/** Design reminder: utility formatting should support premium retail clarity without visual noise. */
export const formatPrice = (value: number) =>
  new Intl.NumberFormat('ru-RU', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(value);
EOF

cat <<'EOF' > src/shared/lib/debounce.ts
/** Design reminder: search interactions should feel calm and responsive rather than jittery. */
export const debounce = <T extends (...args: never[]) => void>(fn: T, delay = 300) => {
  let timeoutId: ReturnType<typeof setTimeout> | null = null;

  return (...args: Parameters<T>) => {
    if (timeoutId) {
      clearTimeout(timeoutId);
    }

    timeoutId = setTimeout(() => fn(...args), delay);
  };
};
EOF

cat <<'EOF' > src/shared/lib/storage.ts
/** Design reminder: persistence should quietly protect user context across visits. */
const storageKeys = {
  cart: 'urban-nest-cart',
  wishlist: 'urban-nest-wishlist',
  catalogPrefs: 'urban-nest-catalog-prefs',
} as const;

const isBrowser = typeof window !== 'undefined';

export const storage = {
  keys: storageKeys,
  get<T>(key: string, fallback: T): T {
    if (!isBrowser) {
      return fallback;
    }

    try {
      const raw = window.localStorage.getItem(key);
      return raw ? (JSON.parse(raw) as T) : fallback;
    } catch {
      return fallback;
    }
  },
  set<T>(key: string, value: T) {
    if (!isBrowser) {
      return;
    }

    window.localStorage.setItem(key, JSON.stringify(value));
  },
};
EOF

cat <<'EOF' > src/shared/api/client.ts
/** Design reminder: API helpers should stay reliable and clean so the UI remains composed. */
import { API_BASE_URL } from '@/shared/config/constants';

export async function fetchJson<T>(path: string): Promise<T> {
  const response = await fetch(`${API_BASE_URL}${path}`, {
    cache: 'no-store',
  });

  if (!response.ok) {
    throw new Error(`Request failed with status ${response.status}`);
  }

  return (await response.json()) as T;
}
EOF

cat <<'EOF' > src/entities/product/model/types.ts
/** Design reminder: typed commerce entities create trust, stability, and clear domain language. */
export interface Review {
  rating: number;
  comment: string;
  date: string;
  reviewerName: string;
  reviewerEmail: string;
}

export interface Product {
  id: number;
  title: string;
  description: string;
  category: string;
  price: number;
  discountPercentage: number;
  rating: number;
  stock: number;
  brand?: string;
  thumbnail: string;
  images: string[];
  tags?: string[];
  warrantyInformation?: string;
  shippingInformation?: string;
  availabilityStatus?: string;
  minimumOrderQuantity?: number;
  reviews?: Review[];
}

export interface Category {
  slug: string;
  name: string;
  url: string;
}

export interface ProductListResponse {
  products: Product[];
  total: number;
  skip: number;
  limit: number;
}

export interface CatalogFilters {
  category: string;
  query: string;
  sort: SortOption;
  page: number;
  perPage: number;
}

export type SortOption = 'featured' | 'price-asc' | 'price-desc' | 'rating-desc' | 'title-asc';
EOF

cat <<'EOF' > src/entities/product/model/mappers.ts
/** Design reminder: normalize external data so the interface always feels curated and stable. */
import { Product } from './types';

export const mapProduct = (product: Product): Product => ({
  ...product,
  images: product.images?.length ? product.images : [product.thumbnail],
});
EOF

cat <<'EOF' > src/shared/api/products.ts
/** Design reminder: the data layer should support smooth merchandising and dependable detail pages. */
import { mapProduct } from '@/entities/product/model/mappers';
import { Category, Product, ProductListResponse } from '@/entities/product/model/types';
import { fetchJson } from './client';

export const productsApi = {
  async getAllProducts() {
    const response = await fetchJson<ProductListResponse>('/products?limit=0');
    return response.products.map(mapProduct);
  },
  async getCategories() {
    return fetchJson<Category[]>('/products/categories');
  },
  async getProductById(id: number) {
    const response = await fetchJson<Product>(`/products/${id}`);
    return mapProduct(response);
  },
  async getRelatedProducts(category: string, excludeId: number) {
    const response = await fetchJson<ProductListResponse>(`/products/category/${category}?limit=0`);
    return response.products.map(mapProduct).filter((product) => product.id !== excludeId).slice(0, 4);
  },
};
EOF

cat <<'EOF' > src/entities/cart/model/types.ts
/** Design reminder: cart entities should remain minimal, fast, and persistence-friendly. */
export interface CartItem {
  id: number;
  title: string;
  price: number;
  thumbnail: string;
  quantity: number;
}
EOF

cat <<'EOF' > src/entities/cart/model/selectors.ts
/** Design reminder: totals and summaries should be derived centrally for a mature commerce flow. */
import { createSelector } from '@reduxjs/toolkit';
import { RootState } from '@/app/store';

export const selectCartItems = (state: RootState) => state.cart.items;

export const selectCartTotals = createSelector([selectCartItems], (items) => {
  const subtotal = items.reduce((acc, item) => acc + item.price * item.quantity, 0);
  const delivery = items.length ? 24 : 0;
  const total = subtotal + delivery;
  const itemsCount = items.reduce((acc, item) => acc + item.quantity, 0);

  return { subtotal, delivery, total, itemsCount };
});
EOF

cat <<'EOF' > src/app/store/slices/catalogSlice.ts
/** Design reminder: catalog state must support elegant browsing, configurable pagination, and low-friction filtering. */
import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { CatalogFilters, Category, Product, SortOption } from '@/entities/product/model/types';
import { DEFAULT_PAGE_SIZE } from '@/shared/config/constants';
import { productsApi } from '@/shared/api/products';

interface CatalogState {
  items: Product[];
  categories: Category[];
  filters: CatalogFilters;
  status: 'idle' | 'loading' | 'succeeded' | 'failed';
  categoriesStatus: 'idle' | 'loading' | 'succeeded' | 'failed';
  error: string | null;
}

const initialState: CatalogState = {
  items: [],
  categories: [],
  filters: {
    category: 'all',
    query: '',
    sort: 'featured',
    page: 1,
    perPage: DEFAULT_PAGE_SIZE,
  },
  status: 'idle',
  categoriesStatus: 'idle',
  error: null,
};

export const fetchProducts = createAsyncThunk('catalog/fetchProducts', async () => productsApi.getAllProducts());
export const fetchCategories = createAsyncThunk('catalog/fetchCategories', async () => productsApi.getCategories());

const catalogSlice = createSlice({
  name: 'catalog',
  initialState,
  reducers: {
    setCategory(state, action: PayloadAction<string>) {
      state.filters.category = action.payload;
      state.filters.page = 1;
    },
    setSearchQuery(state, action: PayloadAction<string>) {
      state.filters.query = action.payload;
      state.filters.page = 1;
    },
    setSort(state, action: PayloadAction<SortOption>) {
      state.filters.sort = action.payload;
      state.filters.page = 1;
    },
    setPage(state, action: PayloadAction<number>) {
      state.filters.page = action.payload;
    },
    setPerPage(state, action: PayloadAction<number>) {
      state.filters.perPage = action.payload;
      state.filters.page = 1;
    },
    resetFilters(state) {
      state.filters = initialState.filters;
    },
    hydrateCatalogPreferences(state, action: PayloadAction<Partial<CatalogFilters>>) {
      state.filters = {
        ...state.filters,
        ...action.payload,
      };
    },
  },
  extraReducers: (builder) => {
    builder
      .addCase(fetchProducts.pending, (state) => {
        state.status = 'loading';
        state.error = null;
      })
      .addCase(fetchProducts.fulfilled, (state, action) => {
        state.status = 'succeeded';
        state.items = action.payload;
      })
      .addCase(fetchProducts.rejected, (state, action) => {
        state.status = 'failed';
        state.error = action.error.message ?? 'Не удалось загрузить каталог';
      })
      .addCase(fetchCategories.pending, (state) => {
        state.categoriesStatus = 'loading';
      })
      .addCase(fetchCategories.fulfilled, (state, action) => {
        state.categoriesStatus = 'succeeded';
        state.categories = action.payload;
      })
      .addCase(fetchCategories.rejected, (state) => {
        state.categoriesStatus = 'failed';
      });
  },
});

export const { setCategory, setSearchQuery, setSort, setPage, setPerPage, resetFilters, hydrateCatalogPreferences } =
  catalogSlice.actions;
export default catalogSlice.reducer;
EOF

cat <<'EOF' > src/app/store/slices/productSlice.ts
/** Design reminder: product detail state should support focused storytelling and related discovery. */
import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { Product } from '@/entities/product/model/types';
import { productsApi } from '@/shared/api/products';

interface ProductState {
  current: Product | null;
  related: Product[];
  status: 'idle' | 'loading' | 'succeeded' | 'failed';
  relatedStatus: 'idle' | 'loading' | 'succeeded' | 'failed';
  error: string | null;
}

const initialState: ProductState = {
  current: null,
  related: [],
  status: 'idle',
  relatedStatus: 'idle',
  error: null,
};

export const fetchProductById = createAsyncThunk('product/fetchById', async (id: number) => productsApi.getProductById(id));
export const fetchRelatedProducts = createAsyncThunk(
  'product/fetchRelated',
  async ({ category, excludeId }: { category: string; excludeId: number }) => productsApi.getRelatedProducts(category, excludeId),
);

const productSlice = createSlice({
  name: 'product',
  initialState,
  reducers: {
    clearCurrentProduct(state) {
      state.current = null;
      state.related = [];
      state.status = 'idle';
      state.relatedStatus = 'idle';
      state.error = null;
    },
  },
  extraReducers: (builder) => {
    builder
      .addCase(fetchProductById.pending, (state) => {
        state.status = 'loading';
        state.error = null;
      })
      .addCase(fetchProductById.fulfilled, (state, action) => {
        state.status = 'succeeded';
        state.current = action.payload;
      })
      .addCase(fetchProductById.rejected, (state, action) => {
        state.status = 'failed';
        state.error = action.error.message ?? 'Не удалось загрузить товар';
      })
      .addCase(fetchRelatedProducts.pending, (state) => {
        state.relatedStatus = 'loading';
      })
      .addCase(fetchRelatedProducts.fulfilled, (state, action) => {
        state.relatedStatus = 'succeeded';
        state.related = action.payload;
      })
      .addCase(fetchRelatedProducts.rejected, (state) => {
        state.relatedStatus = 'failed';
      });
  },
});

export const { clearCurrentProduct } = productSlice.actions;
export default productSlice.reducer;
EOF

cat <<'EOF' > src/app/store/slices/cartSlice.ts
/** Design reminder: cart mechanics should feel dependable, immediate, and frictionless. */
import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { Product } from '@/entities/product/model/types';
import { CartItem } from '@/entities/cart/model/types';

interface CartState {
  items: CartItem[];
}

const initialState: CartState = {
  items: [],
};

const cartSlice = createSlice({
  name: 'cart',
  initialState,
  reducers: {
    hydrateCart(state, action: PayloadAction<CartItem[]>) {
      state.items = action.payload;
    },
    addToCart(state, action: PayloadAction<Product>) {
      const existing = state.items.find((item) => item.id === action.payload.id);

      if (existing) {
        existing.quantity += 1;
        return;
      }

      state.items.push({
        id: action.payload.id,
        title: action.payload.title,
        price: action.payload.price,
        thumbnail: action.payload.thumbnail,
        quantity: 1,
      });
    },
    removeFromCart(state, action: PayloadAction<number>) {
      state.items = state.items.filter((item) => item.id !== action.payload);
    },
    increaseQuantity(state, action: PayloadAction<number>) {
      const existing = state.items.find((item) => item.id === action.payload);
      if (existing) {
        existing.quantity += 1;
      }
    },
    decreaseQuantity(state, action: PayloadAction<number>) {
      const existing = state.items.find((item) => item.id === action.payload);
      if (!existing) return;
      if (existing.quantity <= 1) {
        state.items = state.items.filter((item) => item.id !== action.payload);
        return;
      }
      existing.quantity -= 1;
    },
    clearCart(state) {
      state.items = [];
    },
  },
});

export const { hydrateCart, addToCart, removeFromCart, increaseQuantity, decreaseQuantity, clearCart } = cartSlice.actions;
export default cartSlice.reducer;
EOF

cat <<'EOF' > src/app/store/slices/wishlistSlice.ts
/** Design reminder: wishlist interactions should feel lightweight and instantly legible. */
import { createSlice, PayloadAction } from '@reduxjs/toolkit';

interface WishlistState {
  ids: number[];
}

const initialState: WishlistState = {
  ids: [],
};

const wishlistSlice = createSlice({
  name: 'wishlist',
  initialState,
  reducers: {
    hydrateWishlist(state, action: PayloadAction<number[]>) {
      state.ids = action.payload;
    },
    toggleWishlist(state, action: PayloadAction<number>) {
      if (state.ids.includes(action.payload)) {
        state.ids = state.ids.filter((id) => id !== action.payload);
        return;
      }
      state.ids.push(action.payload);
    },
  },
});

export const { hydrateWishlist, toggleWishlist } = wishlistSlice.actions;
export default wishlistSlice.reducer;
EOF

cat <<'EOF' > src/app/store/slices/uiSlice.ts
/** Design reminder: transient UI state should serve navigation and filtering, never overwhelm the experience. */
import { createSlice } from '@reduxjs/toolkit';

interface UiState {
  mobileMenuOpen: boolean;
  filtersOpen: boolean;
}

const initialState: UiState = {
  mobileMenuOpen: false,
  filtersOpen: false,
};

const uiSlice = createSlice({
  name: 'ui',
  initialState,
  reducers: {
    toggleMobileMenu(state) {
      state.mobileMenuOpen = !state.mobileMenuOpen;
    },
    closeMobileMenu(state) {
      state.mobileMenuOpen = false;
    },
    toggleFilters(state) {
      state.filtersOpen = !state.filtersOpen;
    },
    closeFilters(state) {
      state.filtersOpen = false;
    },
  },
});

export const { toggleMobileMenu, closeMobileMenu, toggleFilters, closeFilters } = uiSlice.actions;
export default uiSlice.reducer;
EOF

cat <<'EOF' > src/app/store/index.ts
/** Design reminder: the store is the backbone of a composed commerce experience. */
import { configureStore } from '@reduxjs/toolkit';
import cartReducer from './slices/cartSlice';
import catalogReducer from './slices/catalogSlice';
import productReducer from './slices/productSlice';
import uiReducer from './slices/uiSlice';
import wishlistReducer from './slices/wishlistSlice';

export const makeStore = () =>
  configureStore({
    reducer: {
      catalog: catalogReducer,
      product: productReducer,
      cart: cartReducer,
      wishlist: wishlistReducer,
      ui: uiReducer,
    },
  });

export type AppStore = ReturnType<typeof makeStore>;
export type RootState = ReturnType<AppStore['getState']>;
export type AppDispatch = AppStore['dispatch'];
EOF

cat <<'EOF' > src/app/store/hooks.ts
/** Design reminder: typed hooks preserve confidence as the interface grows. */
'use client';

import { useDispatch, useSelector, useStore } from 'react-redux';
import type { AppDispatch, AppStore, RootState } from './index';

export const useAppDispatch = useDispatch.withTypes<AppDispatch>();
export const useAppSelector = useSelector.withTypes<RootState>();
export const useAppStore = useStore.withTypes<AppStore>();
EOF

cat <<'EOF' > src/app/store/selectors.ts
/** Design reminder: derived selectors keep catalog UX rich without scattering business logic. */
import { createSelector } from '@reduxjs/toolkit';
import { RootState } from './index';

const sortProducts = (products: RootState['catalog']['items'], sort: RootState['catalog']['filters']['sort']) => {
  const copy = [...products];

  switch (sort) {
    case 'price-asc':
      return copy.sort((a, b) => a.price - b.price);
    case 'price-desc':
      return copy.sort((a, b) => b.price - a.price);
    case 'rating-desc':
      return copy.sort((a, b) => b.rating - a.rating);
    case 'title-asc':
      return copy.sort((a, b) => a.title.localeCompare(b.title));
    default:
      return copy.sort((a, b) => b.rating - a.rating || a.price - b.price);
  }
};

export const selectCatalogState = (state: RootState) => state.catalog;
export const selectWishlistIds = (state: RootState) => state.wishlist.ids;

export const selectFilteredProducts = createSelector([selectCatalogState], (catalog) => {
  const query = catalog.filters.query.trim().toLowerCase();

  const filtered = catalog.items.filter((product) => {
    const matchesCategory = catalog.filters.category === 'all' || product.category === catalog.filters.category;
    const matchesQuery =
      !query ||
      product.title.toLowerCase().includes(query) ||
      product.description.toLowerCase().includes(query) ||
      product.category.toLowerCase().includes(query);

    return matchesCategory && matchesQuery;
  });

  return sortProducts(filtered, catalog.filters.sort);
});

export const selectCatalogMeta = createSelector([selectCatalogState, selectFilteredProducts], (catalog, items) => {
  const total = items.length;
  const totalPages = Math.max(1, Math.ceil(total / catalog.filters.perPage));
  const page = Math.min(catalog.filters.page, totalPages);
  const startIndex = (page - 1) * catalog.filters.perPage;
  const endIndex = startIndex + catalog.filters.perPage;

  return {
    total,
    totalPages,
    currentPage: page,
    startIndex,
    endIndex,
  };
});

export const selectPaginatedProducts = createSelector(
  [selectFilteredProducts, selectCatalogMeta],
  (items, meta) => items.slice(meta.startIndex, meta.endIndex),
);

export const selectFeaturedProducts = createSelector([selectCatalogState], (catalog) =>
  [...catalog.items].sort((a, b) => b.rating - a.rating).slice(0, 8),
);

export const selectNewArrivals = createSelector([selectCatalogState], (catalog) =>
  [...catalog.items].sort((a, b) => b.id - a.id).slice(0, 4),
);

export const selectWishlistProducts = createSelector([selectCatalogState, selectWishlistIds], (catalog, ids) =>
  catalog.items.filter((product) => ids.includes(product.id)),
);
EOF

cat <<'EOF' > src/app/providers/StyledComponentsRegistry.tsx
'use client';

/** Design reminder: the registry keeps styled-components elegant and SSR-safe. */
import React, { useState } from 'react';
import { useServerInsertedHTML } from 'next/navigation';
import { ServerStyleSheet, StyleSheetManager } from 'styled-components';

export default function StyledComponentsRegistry({ children }: { children: React.ReactNode }) {
  const [styledComponentsStyleSheet] = useState(() => new ServerStyleSheet());

  useServerInsertedHTML(() => {
    const styles = styledComponentsStyleSheet.getStyleElement();
    styledComponentsStyleSheet.instance.clearTag();
    return <>{styles}</>;
  });

  if (typeof window !== 'undefined') {
    return <>{children}</>;
  }

  return <StyleSheetManager sheet={styledComponentsStyleSheet.instance}>{children}</StyleSheetManager>;
}
EOF

cat <<'EOF' > src/app/providers/Providers.tsx
'use client';

/** Design reminder: providers should create a cohesive, premium shell rather than leak infrastructure into the UI. */
import React, { useEffect, useRef } from 'react';
import { Provider } from 'react-redux';
import { ThemeProvider } from 'styled-components';
import { hydrateCart } from '@/app/store/slices/cartSlice';
import { hydrateCatalogPreferences } from '@/app/store/slices/catalogSlice';
import { hydrateWishlist } from '@/app/store/slices/wishlistSlice';
import { AppStore, makeStore } from '@/app/store';
import { useAppSelector } from '@/app/store/hooks';
import { theme } from '@/shared/styles/theme';
import { GlobalStyles } from '@/shared/styles/global-styles';
import { storage } from '@/shared/lib/storage';

function PersistGate() {
  const store = React.useContext((Provider as unknown as { context: React.Context<AppStore | null> }).context);
  const cartItems = useAppSelector((state) => state.cart.items);
  const wishlistIds = useAppSelector((state) => state.wishlist.ids);
  const filters = useAppSelector((state) => state.catalog.filters);

  useEffect(() => {
    if (!store) return;

    store.dispatch(hydrateCart(storage.get(storage.keys.cart, [])));
    store.dispatch(hydrateWishlist(storage.get(storage.keys.wishlist, [])));
    store.dispatch(
      hydrateCatalogPreferences(
        storage.get(storage.keys.catalogPrefs, {
          category: 'all',
          query: '',
          sort: 'featured',
          page: 1,
          perPage: filters.perPage,
        }),
      ),
    );
  }, [store, filters.perPage]);

  useEffect(() => {
    storage.set(storage.keys.cart, cartItems);
  }, [cartItems]);

  useEffect(() => {
    storage.set(storage.keys.wishlist, wishlistIds);
  }, [wishlistIds]);

  useEffect(() => {
    storage.set(storage.keys.catalogPrefs, filters);
  }, [filters]);

  return null;
}

export function Providers({ children }: { children: React.ReactNode }) {
  const storeRef = useRef<AppStore | null>(null);

  if (!storeRef.current) {
    storeRef.current = makeStore();
  }

  return (
    <Provider store={storeRef.current}>
      <ThemeProvider theme={theme}>
        <GlobalStyles />
        <PersistGate />
        {children}
      </ThemeProvider>
    </Provider>
  );
}
EOF

cat <<'EOF' > src/shared/ui/Container.tsx
/** Design reminder: containers should privilege breathing room and editorial alignment over cramped grids. */
'use client';

import styled from 'styled-components';

const Container = styled.div`
  width: min(100%, 1200px);
  margin: 0 auto;
  padding-inline: clamp(1rem, 2vw, 2rem);
`;

export default Container;
EOF

cat <<'EOF' > src/shared/ui/Section.tsx
/** Design reminder: sections should feel like calm editorial chapters with deliberate vertical rhythm. */
'use client';

import styled from 'styled-components';

const Section = styled.section<{ $soft?: boolean }>`
  padding-block: clamp(3rem, 8vw, 6rem);
  background: ${({ theme, $soft }) => ($soft ? theme.colors.surface : 'transparent')};
`;

export default Section;
EOF

cat <<'EOF' > src/shared/ui/Button.tsx
/** Design reminder: buttons should be calm but decisive, with tactile depth and premium contrast. */
'use client';

import styled, { css } from 'styled-components';

const variants = {
  primary: css`
    background: ${({ theme }) => theme.colors.text};
    color: ${({ theme }) => theme.colors.surface};
    box-shadow: ${({ theme }) => theme.shadows.soft};
  `,
  secondary: css`
    background: ${({ theme }) => theme.colors.surface};
    color: ${({ theme }) => theme.colors.text};
    border: 1px solid ${({ theme }) => theme.colors.border};
  `,
  ghost: css`
    background: transparent;
    color: ${({ theme }) => theme.colors.text};
    border: 1px solid ${({ theme }) => theme.colors.border};
  `,
};

const Button = styled.button<{ $variant?: keyof typeof variants; $full?: boolean }>`
  border: none;
  border-radius: ${({ theme }) => theme.radii.pill};
  padding: 0.95rem 1.4rem;
  font-size: 0.95rem;
  font-weight: 600;
  letter-spacing: 0.01em;
  width: ${({ $full }) => ($full ? '100%' : 'auto')};
  transition: transform 180ms ease, box-shadow 180ms ease, background 180ms ease, color 180ms ease;
  ${({ $variant = 'primary' }) => variants[$variant]};

  &:hover {
    transform: translateY(-1px);
    box-shadow: ${({ theme }) => theme.shadows.card};
  }
`;

export default Button;
EOF

cat <<'EOF' > src/shared/ui/Input.tsx
/** Design reminder: form controls should feel soft, spacious, and quietly high-end. */
'use client';

import styled from 'styled-components';

const Input = styled.input`
  width: 100%;
  min-height: 52px;
  border-radius: ${({ theme }) => theme.radii.pill};
  border: 1px solid ${({ theme }) => theme.colors.border};
  background: rgba(255, 250, 244, 0.92);
  padding: 0 1rem;
  color: ${({ theme }) => theme.colors.text};
  transition: border-color 180ms ease, box-shadow 180ms ease;

  &:focus {
    outline: none;
    border-color: ${({ theme }) => theme.colors.accent};
    box-shadow: 0 0 0 4px rgba(85, 107, 93, 0.12);
  }
`;

export default Input;
EOF

cat <<'EOF' > src/shared/ui/Badge.tsx
/** Design reminder: badges should read like curated labels, not noisy UI stickers. */
'use client';

import styled from 'styled-components';

const Badge = styled.span`
  display: inline-flex;
  align-items: center;
  gap: 0.3rem;
  padding: 0.45rem 0.85rem;
  border-radius: ${({ theme }) => theme.radii.pill};
  background: ${({ theme }) => theme.colors.accentSoft};
  color: ${({ theme }) => theme.colors.accent};
  font-size: 0.78rem;
  font-weight: 700;
  letter-spacing: 0.14em;
  text-transform: uppercase;
`;

export default Badge;
EOF

cat <<'EOF' > src/shared/ui/EmptyState.tsx
/** Design reminder: empty states should still feel branded, helpful, and intentional. */
'use client';

import Link from 'next/link';
import styled from 'styled-components';
import Button from './Button';

const Wrapper = styled.div`
  display: grid;
  gap: 1rem;
  place-items: start;
  padding: 2rem;
  border-radius: ${({ theme }) => theme.radii.lg};
  background: rgba(255, 250, 244, 0.9);
  border: 1px solid ${({ theme }) => theme.colors.border};
  box-shadow: ${({ theme }) => theme.shadows.soft};
`;

export default function EmptyState({ title, description, href, action }: { title: string; description: string; href: string; action: string }) {
  return (
    <Wrapper>
      <h3>{title}</h3>
      <p>{description}</p>
      <Link href={href}>
        <Button as="span">{action}</Button>
      </Link>
    </Wrapper>
  );
}
EOF

cat <<'EOF' > src/shared/ui/Pagination.tsx
/** Design reminder: pagination should remain configurable, legible, and visually lightweight. */
'use client';

import styled from 'styled-components';
import Button from './Button';

const Row = styled.div`
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
  align-items: center;
  justify-content: space-between;
`;

const Numbers = styled.div`
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
`;

export default function Pagination({ currentPage, totalPages, onPageChange }: { currentPage: number; totalPages: number; onPageChange: (page: number) => void }) {
  const pages = Array.from({ length: totalPages }, (_, index) => index + 1);

  return (
    <Row>
      <Button $variant="secondary" disabled={currentPage === 1} onClick={() => onPageChange(currentPage - 1)}>
        Назад
      </Button>
      <Numbers>
        {pages.map((page) => (
          <Button key={page} $variant={page === currentPage ? 'primary' : 'ghost'} onClick={() => onPageChange(page)}>
            {page}
          </Button>
        ))}
      </Numbers>
      <Button $variant="secondary" disabled={currentPage === totalPages} onClick={() => onPageChange(currentPage + 1)}>
        Далее
      </Button>
    </Row>
  );
}
EOF

cat <<'EOF' > src/features/add-to-cart/ui/AddToCartButton.tsx
/** Design reminder: cart entry points should feel decisive and trustworthy. */
'use client';

import { Product } from '@/entities/product/model/types';
import { addToCart } from '@/app/store/slices/cartSlice';
import { useAppDispatch } from '@/app/store/hooks';
import Button from '@/shared/ui/Button';

export default function AddToCartButton({ product, full }: { product: Product; full?: boolean }) {
  const dispatch = useAppDispatch();

  return (
    <Button $full={full} onClick={() => dispatch(addToCart(product))}>
      Добавить в корзину
    </Button>
  );
}
EOF

cat <<'EOF' > src/features/toggle-wishlist/ui/WishlistToggleButton.tsx
/** Design reminder: wishlist toggles should act like refined, low-noise micro-interactions. */
'use client';

import styled from 'styled-components';
import { toggleWishlist } from '@/app/store/slices/wishlistSlice';
import { useAppDispatch, useAppSelector } from '@/app/store/hooks';

const Toggle = styled.button<{ $active: boolean }>`
  width: 48px;
  height: 48px;
  border-radius: 50%;
  border: 1px solid ${({ theme }) => theme.colors.border};
  background: ${({ $active, theme }) => ($active ? theme.colors.text : 'rgba(255, 250, 244, 0.9)')};
  color: ${({ $active, theme }) => ($active ? theme.colors.surface : theme.colors.text)};
  font-size: 1.15rem;
  transition: transform 180ms ease;

  &:hover {
    transform: scale(1.04);
  }
`;

export default function WishlistToggleButton({ productId }: { productId: number }) {
  const dispatch = useAppDispatch();
  const active = useAppSelector((state) => state.wishlist.ids.includes(productId));

  return (
    <Toggle $active={active} onClick={() => dispatch(toggleWishlist(productId))} aria-label="Toggle wishlist">
      {active ? '♥' : '♡'}
    </Toggle>
  );
}
EOF

cat <<'EOF' > src/features/change-quantity/ui/QuantityControl.tsx
/** Design reminder: quantity controls should remain clean, tactile, and unmistakably functional. */
'use client';

import styled from 'styled-components';
import { decreaseQuantity, increaseQuantity } from '@/app/store/slices/cartSlice';
import { useAppDispatch } from '@/app/store/hooks';

const Wrap = styled.div`
  display: inline-flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.35rem;
  border-radius: ${({ theme }) => theme.radii.pill};
  background: ${({ theme }) => theme.colors.surface};
  border: 1px solid ${({ theme }) => theme.colors.border};
`;

const SmallButton = styled.button`
  width: 36px;
  height: 36px;
  border-radius: 50%;
  border: none;
  background: ${({ theme }) => theme.colors.surfaceAlt};
`;

export default function QuantityControl({ productId, quantity }: { productId: number; quantity: number }) {
  const dispatch = useAppDispatch();

  return (
    <Wrap>
      <SmallButton onClick={() => dispatch(decreaseQuantity(productId))}>−</SmallButton>
      <strong>{quantity}</strong>
      <SmallButton onClick={() => dispatch(increaseQuantity(productId))}>+</SmallButton>
    </Wrap>
  );
}
EOF

cat <<'EOF' > src/features/search-products/ui/SearchBar.tsx
/** Design reminder: search must feel immediate but calm, preserving a premium browsing rhythm. */
'use client';

import { useEffect, useMemo, useState } from 'react';
import { debounce } from '@/shared/lib/debounce';
import Input from '@/shared/ui/Input';

export default function SearchBar({ value, onCommit }: { value: string; onCommit: (value: string) => void }) {
  const [query, setQuery] = useState(value);
  const debouncedCommit = useMemo(() => debounce((nextValue: string) => onCommit(nextValue), 280), [onCommit]);

  useEffect(() => {
    setQuery(value);
  }, [value]);

  return (
    <Input
      value={query}
      placeholder="Поиск по названию, описанию или категории"
      onChange={(event) => {
        const nextValue = event.target.value;
        setQuery(nextValue);
        debouncedCommit(nextValue);
      }}
    />
  );
}
EOF

cat <<'EOF' > src/features/sort-products/ui/SortSelect.tsx
/** Design reminder: sorting controls should stay native, typed, and elegantly quiet. */
'use client';

import styled from 'styled-components';
import { SortOption } from '@/entities/product/model/types';

const Select = styled.select`
  min-height: 52px;
  border-radius: ${({ theme }) => theme.radii.pill};
  border: 1px solid ${({ theme }) => theme.colors.border};
  background: rgba(255, 250, 244, 0.92);
  padding: 0 1rem;
`;

export default function SortSelect({ value, onChange }: { value: SortOption; onChange: (value: SortOption) => void }) {
  return (
    <Select value={value} onChange={(event) => onChange(event.target.value as SortOption)}>
      <option value="featured">По умолчанию</option>
      <option value="price-asc">Цена: по возрастанию</option>
      <option value="price-desc">Цена: по убыванию</option>
      <option value="rating-desc">По рейтингу</option>
      <option value="title-asc">По названию</option>
    </Select>
  );
}
EOF

cat <<'EOF' > src/features/filters/ui/FiltersSidebar.tsx
/** Design reminder: filters should frame discovery like a curated showroom menu. */
'use client';

import styled from 'styled-components';
import { Category } from '@/entities/product/model/types';
import Button from '@/shared/ui/Button';

const Panel = styled.aside<{ $mobile?: boolean; $open?: boolean }>`
  display: grid;
  gap: 1rem;
  align-content: start;
  padding: 1.5rem;
  border-radius: ${({ theme }) => theme.radii.lg};
  background: rgba(255, 250, 244, 0.9);
  border: 1px solid ${({ theme }) => theme.colors.border};
  box-shadow: ${({ theme }) => theme.shadows.soft};

  @media (max-width: 900px) {
    display: ${({ $mobile, $open }) => ($mobile ? ($open ? 'grid' : 'none') : 'grid')};
  }
`;

const CategoryButton = styled.button<{ $active: boolean }>`
  text-align: left;
  border: none;
  background: ${({ $active, theme }) => ($active ? theme.colors.surfaceAlt : 'transparent')};
  color: ${({ theme }) => theme.colors.text};
  padding: 0.8rem 1rem;
  border-radius: ${({ theme }) => theme.radii.md};
`;

export default function FiltersSidebar({
  categories,
  activeCategory,
  onSelectCategory,
  onReset,
  mobile,
  open,
}: {
  categories: Category[];
  activeCategory: string;
  onSelectCategory: (category: string) => void;
  onReset: () => void;
  mobile?: boolean;
  open?: boolean;
}) {
  return (
    <Panel $mobile={mobile} $open={open}>
      <div>
        <h3>Фильтры</h3>
        <p>Подбери товары по назначению комнаты и настроению интерьера.</p>
      </div>
      <CategoryButton $active={activeCategory === 'all'} onClick={() => onSelectCategory('all')}>
        Все категории
      </CategoryButton>
      {categories.map((category) => (
        <CategoryButton
          key={category.slug}
          $active={activeCategory === category.slug}
          onClick={() => onSelectCategory(category.slug)}
        >
          {category.name}
        </CategoryButton>
      ))}
      <Button $variant="ghost" onClick={onReset}>
        Сбросить фильтры
      </Button>
    </Panel>
  );
}
EOF

cat <<'EOF' > src/entities/product/ui/ProductPrice.tsx
/** Design reminder: pricing should read clearly with understated emphasis. */
'use client';

import styled from 'styled-components';
import { formatPrice } from '@/shared/lib/formatPrice';

const Price = styled.div`
  display: flex;
  align-items: baseline;
  gap: 0.75rem;
`;

const Current = styled.strong`
  font-size: 1.25rem;
`;

const Discount = styled.span`
  color: ${({ theme }) => theme.colors.textMuted};
`;

export default function ProductPrice({ price, discountPercentage }: { price: number; discountPercentage: number }) {
  const initialPrice = price / (1 - discountPercentage / 100);

  return (
    <Price>
      <Current>{formatPrice(price)}</Current>
      <Discount>{Math.round(discountPercentage)}% off · {formatPrice(initialPrice)}</Discount>
    </Price>
  );
}
EOF

cat <<'EOF' > src/entities/product/ui/ProductGallery.tsx
/** Design reminder: galleries should feel expansive and tactile, like a digital showroom spread. */
'use client';

import Image from 'next/image';
import { useState } from 'react';
import styled from 'styled-components';

const Wrap = styled.div`
  display: grid;
  gap: 1rem;
`;

const Primary = styled.div`
  position: relative;
  overflow: hidden;
  border-radius: ${({ theme }) => theme.radii.lg};
  min-height: 420px;
  background: ${({ theme }) => theme.colors.surface};
`;

const Thumbs = styled.div`
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 0.75rem;
`;

const Thumb = styled.button<{ $active: boolean }>`
  position: relative;
  overflow: hidden;
  border-radius: ${({ theme }) => theme.radii.md};
  border: 1px solid ${({ theme, $active }) => ($active ? theme.colors.text : theme.colors.border)};
  min-height: 88px;
  background: ${({ theme }) => theme.colors.surface};
`;

export default function ProductGallery({ images, title }: { images: string[]; title: string }) {
  const [activeImage, setActiveImage] = useState(images[0]);

  return (
    <Wrap>
      <Primary>
        <Image src={activeImage} alt={title} fill style={{ objectFit: 'cover' }} sizes="(max-width: 768px) 100vw, 50vw" />
      </Primary>
      <Thumbs>
        {images.map((image) => (
          <Thumb key={image} $active={image === activeImage} onClick={() => setActiveImage(image)}>
            <Image src={image} alt={title} fill style={{ objectFit: 'cover' }} sizes="120px" />
          </Thumb>
        ))}
      </Thumbs>
    </Wrap>
  );
}
EOF

cat <<'EOF' > src/entities/product/ui/ProductCard.tsx
/** Design reminder: cards should blend commerce clarity with editorial warmth and visual depth. */
'use client';

import Image from 'next/image';
import Link from 'next/link';
import styled from 'styled-components';
import { Product } from '@/entities/product/model/types';
import { routes } from '@/shared/config/routes';
import ProductPrice from './ProductPrice';
import WishlistToggleButton from '@/features/toggle-wishlist/ui/WishlistToggleButton';
import AddToCartButton from '@/features/add-to-cart/ui/AddToCartButton';

const Card = styled.article`
  display: grid;
  gap: 1rem;
  padding: 1rem;
  border-radius: ${({ theme }) => theme.radii.lg};
  background: rgba(255, 250, 244, 0.92);
  border: 1px solid ${({ theme }) => theme.colors.border};
  box-shadow: ${({ theme }) => theme.shadows.soft};
  transition: transform 220ms ease, box-shadow 220ms ease;

  &:hover {
    transform: translateY(-4px);
    box-shadow: ${({ theme }) => theme.shadows.card};
  }
`;

const ImageWrap = styled.div`
  position: relative;
  overflow: hidden;
  border-radius: ${({ theme }) => theme.radii.md};
  min-height: 260px;
  background: ${({ theme }) => theme.colors.surface};
`;

const TopRow = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: start;
  gap: 1rem;
`;

const Meta = styled.div`
  display: grid;
  gap: 0.5rem;
`;

const Category = styled.span`
  font-size: 0.75rem;
  text-transform: uppercase;
  letter-spacing: 0.14em;
  color: ${({ theme }) => theme.colors.textMuted};
`;

export default function ProductCard({ product }: { product: Product }) {
  return (
    <Card>
      <Link href={routes.product(product.id)}>
        <ImageWrap>
          <Image src={product.thumbnail} alt={product.title} fill style={{ objectFit: 'cover' }} sizes="(max-width: 768px) 100vw, 25vw" />
        </ImageWrap>
      </Link>
      <TopRow>
        <Meta>
          <Category>{product.category.replace('-', ' ')}</Category>
          <Link href={routes.product(product.id)}>
            <h3>{product.title}</h3>
          </Link>
          <p>{product.description.slice(0, 88)}...</p>
          <ProductPrice price={product.price} discountPercentage={product.discountPercentage} />
        </Meta>
        <WishlistToggleButton productId={product.id} />
      </TopRow>
      <AddToCartButton product={product} full />
    </Card>
  );
}
EOF

cat <<'EOF' > src/widgets/CatalogGrid/index.tsx
/** Design reminder: catalog grids should feel airy, consistent, and easy to scan across breakpoints. */
'use client';

import styled from 'styled-components';
import { Product } from '@/entities/product/model/types';
import ProductCard from '@/entities/product/ui/ProductCard';

const Grid = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 1.25rem;
`;

const Skeleton = styled.div`
  min-height: 360px;
  border-radius: ${({ theme }) => theme.radii.lg};
  background: linear-gradient(120deg, rgba(255,255,255,0.35), rgba(235,228,216,0.95), rgba(255,255,255,0.35));
  background-size: 200% 100%;
  animation: shimmer 1.2s infinite linear;

  @keyframes shimmer {
    from { background-position: 200% 0; }
    to { background-position: -200% 0; }
  }
`;

export default function CatalogGrid({ products, loading = false }: { products: Product[]; loading?: boolean }) {
  if (loading) {
    return (
      <Grid>
        {Array.from({ length: 8 }, (_, index) => (
          <Skeleton key={index} />
        ))}
      </Grid>
    );
  }

  return (
    <Grid>
      {products.map((product) => (
        <ProductCard key={product.id} product={product} />
      ))}
    </Grid>
  );
}
EOF

cat <<'EOF' > src/widgets/RelatedProducts/index.tsx
/** Design reminder: related products should extend the story of the current room and mood. */
'use client';

import styled from 'styled-components';
import { Product } from '@/entities/product/model/types';
import CatalogGrid from '@/widgets/CatalogGrid';

const Wrap = styled.div`
  display: grid;
  gap: 1.5rem;
`;

export default function RelatedProducts({ products }: { products: Product[] }) {
  return (
    <Wrap>
      <div>
        <h2>Похожие товары</h2>
        <p>Подобрали варианты в той же эстетике и категории.</p>
      </div>
      <CatalogGrid products={products} />
    </Wrap>
  );
}
EOF

cat <<'EOF' > src/widgets/CartSummary/index.tsx
/** Design reminder: cart summary should present totals with calm confidence and strong hierarchy. */
'use client';

import styled from 'styled-components';
import { formatPrice } from '@/shared/lib/formatPrice';
import Button from '@/shared/ui/Button';

const Card = styled.aside`
  display: grid;
  gap: 1rem;
  padding: 1.5rem;
  border-radius: ${({ theme }) => theme.radii.lg};
  background: rgba(255, 250, 244, 0.96);
  border: 1px solid ${({ theme }) => theme.colors.border};
  box-shadow: ${({ theme }) => theme.shadows.soft};
  position: sticky;
  top: 96px;
`;

const Row = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
`;

export default function CartSummary({ subtotal, delivery, total, onClear }: { subtotal: number; delivery: number; total: number; onClear: () => void }) {
  return (
    <Card>
      <h3>Итого по заказу</h3>
      <Row><span>Товары</span><strong>{formatPrice(subtotal)}</strong></Row>
      <Row><span>Доставка</span><strong>{formatPrice(delivery)}</strong></Row>
      <Row><span>Promo</span><span>—</span></Row>
      <Row><span>Всего</span><strong>{formatPrice(total)}</strong></Row>
      <Button>Перейти к оформлению</Button>
      <Button $variant="ghost" onClick={onClear}>Очистить корзину</Button>
    </Card>
  );
}
EOF

cat <<'EOF' > src/widgets/Header/index.tsx
/** Design reminder: the header should feel airy, navigable, and quietly premium on every route. */
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import styled from 'styled-components';
import { useAppDispatch, useAppSelector } from '@/app/store/hooks';
import { closeMobileMenu, toggleMobileMenu } from '@/app/store/slices/uiSlice';
import { NAV_LINKS } from '@/shared/config/constants';
import { selectCartTotals } from '@/entities/cart/model/selectors';
import Container from '@/shared/ui/Container';

const Shell = styled.header`
  position: sticky;
  top: 0;
  z-index: 30;
  backdrop-filter: blur(18px);
  background: rgba(246, 240, 231, 0.82);
  border-bottom: 1px solid ${({ theme }) => theme.colors.border};
`;

const Row = styled(Container)`
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1.25rem;
  min-height: 84px;
`;

const Brand = styled(Link)`
  font-family: ${({ theme }) => theme.fonts.display};
  font-size: 1.5rem;
  letter-spacing: -0.04em;
`;

const Nav = styled.nav<{ $open: boolean }>`
  display: flex;
  align-items: center;
  gap: 1rem;

  @media (max-width: 920px) {
    position: absolute;
    left: 1rem;
    right: 1rem;
    top: calc(100% + 0.75rem);
    display: ${({ $open }) => ($open ? 'grid' : 'none')};
    padding: 1rem;
    border-radius: ${({ theme }) => theme.radii.lg};
    background: ${({ theme }) => theme.colors.surface};
    box-shadow: ${({ theme }) => theme.shadows.lifted};
  }
`;

const NavLink = styled(Link)<{ $active: boolean }>`
  color: ${({ $active, theme }) => ($active ? theme.colors.text : theme.colors.textMuted)};
  padding-bottom: 0.35rem;
  border-bottom: 2px solid ${({ $active, theme }) => ($active ? theme.colors.text : 'transparent')};
`;

const Counter = styled.span`
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 24px;
  height: 24px;
  padding-inline: 0.35rem;
  border-radius: 999px;
  background: ${({ theme }) => theme.colors.text};
  color: ${({ theme }) => theme.colors.surface};
  font-size: 0.75rem;
`;

const MenuButton = styled.button`
  display: none;
  border: none;
  background: transparent;

  @media (max-width: 920px) {
    display: inline-flex;
  }
`;

export default function Header() {
  const pathname = usePathname();
  const dispatch = useAppDispatch();
  const mobileMenuOpen = useAppSelector((state) => state.ui.mobileMenuOpen);
  const wishlistCount = useAppSelector((state) => state.wishlist.ids.length);
  const { itemsCount } = useAppSelector(selectCartTotals);

  return (
    <Shell>
      <Row>
        <Brand href="/">Urban Nest</Brand>
        <MenuButton onClick={() => dispatch(toggleMobileMenu())}>Меню</MenuButton>
        <Nav $open={mobileMenuOpen}>
          {NAV_LINKS.map((item) => (
            <NavLink
              key={item.href}
              href={item.href}
              $active={pathname === item.href}
              onClick={() => dispatch(closeMobileMenu())}
            >
              {item.label}
              {item.href === '/wishlist' && wishlistCount > 0 ? <Counter>{wishlistCount}</Counter> : null}
              {item.href === '/cart' && itemsCount > 0 ? <Counter>{itemsCount}</Counter> : null}
            </NavLink>
          ))}
        </Nav>
      </Row>
    </Shell>
  );
}
EOF

cat <<'EOF' > src/widgets/Footer/index.tsx
/** Design reminder: the footer should close the experience like a calm editorial signature. */
'use client';

import styled from 'styled-components';
import Container from '@/shared/ui/Container';

const Shell = styled.footer`
  margin-top: 4rem;
  padding-block: 2rem 3rem;
  border-top: 1px solid ${({ theme }) => theme.colors.border};
`;

const Grid = styled(Container)`
  display: grid;
  gap: 1rem;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
`;

export default function Footer() {
  return (
    <Shell>
      <Grid>
        <div>
          <h3>Urban Nest Store</h3>
          <p>Современный магазин предметов для дома, собранный как зрелый frontend-проект для портфолио.</p>
        </div>
        <div>
          <h4>Навигация</h4>
          <p>Каталог, wishlist, cart, about, contacts и динамическая карточка товара.</p>
        </div>
        <div>
          <h4>Контакты</h4>
          <p>hello@urbannest.store</p>
          <p>+1 (415) 555-0147</p>
        </div>
      </Grid>
    </Shell>
  );
}
EOF

cat <<'EOF' > src/widgets/Hero/index.tsx
/** Design reminder: the hero must establish warm Scandinavian calm, premium space, and strong narrative focus. */
'use client';

import Link from 'next/link';
import Image from 'next/image';
import styled from 'styled-components';
import { HERO_IMAGE } from '@/shared/config/constants';
import { routes } from '@/shared/config/routes';
import Button from '@/shared/ui/Button';
import Container from '@/shared/ui/Container';
import Badge from '@/shared/ui/Badge';

const Section = styled.section`
  padding-block: clamp(2.5rem, 7vw, 5.5rem) 3rem;
`;

const Frame = styled(Container)`
  display: grid;
  gap: 1.5rem;
  grid-template-columns: 1.1fr 0.9fr;
  align-items: end;

  @media (max-width: 960px) {
    grid-template-columns: 1fr;
  }
`;

const Content = styled.div`
  display: grid;
  gap: 1.5rem;
  align-content: start;
`;

const Eyebrow = styled.div`
  display: flex;
  gap: 0.75rem;
  flex-wrap: wrap;
`;

const Title = styled.h1`
  font-size: clamp(3.25rem, 10vw, 6rem);
  line-height: 0.94;
`;

const Actions = styled.div`
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
`;

const Visual = styled.div`
  position: relative;
  min-height: 600px;
  border-radius: ${({ theme }) => theme.radii.lg};
  overflow: hidden;
  box-shadow: ${({ theme }) => theme.shadows.lifted};

  @media (max-width: 960px) {
    min-height: 420px;
  }
`;

const Overlay = styled.div`
  position: absolute;
  inset: 0;
  background: linear-gradient(180deg, rgba(246,240,231,0.02) 0%, rgba(32,26,23,0.08) 100%);
`;

export default function Hero() {
  return (
    <Section>
      <Frame>
        <Content>
          <Eyebrow>
            <Badge>Curated living</Badge>
            <Badge>SS26 interior edit</Badge>
          </Eyebrow>
          <Title>Дом, который ощущается спокойнее с первого взгляда.</Title>
          <p>
            Urban Nest Store — это цифровой showroom с мебелью, декором и мягкими повседневными деталями.
            Проект демонстрирует не только визуальную подачу, но и зрелую frontend-архитектуру с Redux Toolkit,
            динамическими маршрутами, поиском, фильтрами и local persistence.
          </p>
          <Actions>
            <Link href={routes.catalog}><Button as="span">Открыть каталог</Button></Link>
            <Link href={routes.about}><Button as="span" $variant="secondary">Узнать о бренде</Button></Link>
          </Actions>
        </Content>
        <Visual>
          <Image src={HERO_IMAGE} alt="Urban Nest Hero" fill priority style={{ objectFit: 'cover' }} sizes="(max-width: 960px) 100vw, 50vw" />
          <Overlay />
        </Visual>
      </Frame>
    </Section>
  );
}
EOF

cat <<'EOF' > src/widgets/CategoryStrip/index.tsx
/** Design reminder: category highlights should look curated like magazine callouts, not plain shortcuts. */
'use client';

import Image from 'next/image';
import Link from 'next/link';
import styled from 'styled-components';
import { Category } from '@/entities/product/model/types';
import { CATEGORY_IMAGE } from '@/shared/config/constants';
import Button from '@/shared/ui/Button';
import Container from '@/shared/ui/Container';
import Section from '@/shared/ui/Section';

const Wrap = styled(Container)`
  display: grid;
  gap: 1.5rem;
  grid-template-columns: 1fr 0.95fr;
  align-items: stretch;

  @media (max-width: 980px) {
    grid-template-columns: 1fr;
  }
`;

const Categories = styled.div`
  display: grid;
  gap: 1rem;
  grid-template-columns: repeat(2, minmax(0, 1fr));
`;

const Item = styled(Link)`
  display: grid;
  gap: 0.35rem;
  padding: 1.25rem;
  border-radius: ${({ theme }) => theme.radii.lg};
  background: rgba(255, 250, 244, 0.92);
  border: 1px solid ${({ theme }) => theme.colors.border};
  box-shadow: ${({ theme }) => theme.shadows.soft};
`;

const Promo = styled.div`
  position: relative;
  min-height: 100%;
  overflow: hidden;
  border-radius: ${({ theme }) => theme.radii.lg};
`;

const PromoText = styled.div`
  position: absolute;
  inset: auto 1.25rem 1.25rem 1.25rem;
  display: grid;
  gap: 0.75rem;
  padding: 1.25rem;
  border-radius: ${({ theme }) => theme.radii.md};
  background: rgba(32, 26, 23, 0.65);
  color: #fefcf8;
`;

export default function CategoryStrip({ categories }: { categories: Category[] }) {
  return (
    <Section>
      <Wrap>
        <div>
          <h2>Популярные категории</h2>
          <p>Быстрый вход в самые востребованные направления магазина.</p>
          <Categories>
            {categories.slice(0, 6).map((category) => (
              <Item key={category.slug} href={`/catalog?category=${category.slug}`}>
                <strong>{category.name}</strong>
                <span>Перейти в curated selection</span>
              </Item>
            ))}
          </Categories>
        </div>
        <Promo>
          <Image src={CATEGORY_IMAGE} alt="Dining category" fill style={{ objectFit: 'cover' }} sizes="(max-width: 980px) 100vw, 45vw" />
          <PromoText>
            <h3>Seasonal dining edit</h3>
            <p>Тёплые формы, мягкие материалы и спокойная палитра для дома.</p>
            <Link href="/catalog?category=furniture"><Button as="span" $variant="secondary">Смотреть подборку</Button></Link>
          </PromoText>
        </Promo>
      </Wrap>
    </Section>
  );
}
EOF

cat <<'EOF' > src/widgets/Benefits/index.tsx
/** Design reminder: benefit blocks should feel like confident brand notes, not generic feature lists. */
'use client';

import styled from 'styled-components';
import Container from '@/shared/ui/Container';
import Section from '@/shared/ui/Section';

const Grid = styled(Container)`
  display: grid;
  gap: 1rem;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
`;

const Card = styled.article`
  display: grid;
  gap: 0.75rem;
  padding: 1.5rem;
  border-radius: ${({ theme }) => theme.radii.lg};
  background: rgba(255, 250, 244, 0.9);
  border: 1px solid ${({ theme }) => theme.colors.border};
`;

const benefits = [
  { title: 'Curated collections', text: 'Каталог собран как интерьерная подборка, а не просто список SKU.' },
  { title: 'Typed architecture', text: 'Строгие типы DTO, селекторы, slices и переиспользуемые UI-слои.' },
  { title: 'Smooth shopping flow', text: 'Wishlist, cart, quantity controls и persistence делают UX зрелым.' },
  { title: 'Responsive showroom', text: 'Спокойная адаптивность без визуального шума на любых экранах.' },
];

export default function Benefits() {
  return (
    <Section $soft>
      <Grid>
        {benefits.map((benefit) => (
          <Card key={benefit.title}>
            <h3>{benefit.title}</h3>
            <p>{benefit.text}</p>
          </Card>
        ))}
      </Grid>
    </Section>
  );
}
EOF

cat <<'EOF' > src/widgets/Newsletter/index.tsx
/** Design reminder: newsletter blocks should extend brand warmth and offer a polished content break. */
'use client';

import styled from 'styled-components';
import Button from '@/shared/ui/Button';
import Container from '@/shared/ui/Container';
import Input from '@/shared/ui/Input';
import Section from '@/shared/ui/Section';

const Card = styled(Container)`
  display: grid;
  gap: 1rem;
  padding: clamp(1.5rem, 4vw, 2.5rem);
  border-radius: ${({ theme }) => theme.radii.lg};
  background: linear-gradient(135deg, rgba(255,250,244,0.92), rgba(221,230,220,0.95));
  border: 1px solid ${({ theme }) => theme.colors.border};
  box-shadow: ${({ theme }) => theme.shadows.soft};
`;

const Form = styled.form`
  display: grid;
  grid-template-columns: 1fr auto;
  gap: 1rem;

  @media (max-width: 720px) {
    grid-template-columns: 1fr;
  }
`;

export default function Newsletter() {
  return (
    <Section>
      <Card>
        <div>
          <h2>Новые интерьерные дропы без визуального шума</h2>
          <p>Подпишись на подборки, новинки и сезонные коллекции Urban Nest.</p>
        </div>
        <Form>
          <Input type="email" placeholder="your@email.com" />
          <Button type="submit">Подписаться</Button>
        </Form>
      </Card>
    </Section>
  );
}
EOF

cat <<'EOF' > src/views/home/HomeView.tsx
/** Design reminder: the home page should feel like a premium digital showroom with strong editorial pacing. */
'use client';

import { useEffect } from 'react';
import { useAppDispatch, useAppSelector } from '@/app/store/hooks';
import { selectFeaturedProducts, selectNewArrivals } from '@/app/store/selectors';
import { fetchCategories, fetchProducts } from '@/app/store/slices/catalogSlice';
import CatalogGrid from '@/widgets/CatalogGrid';
import Benefits from '@/widgets/Benefits';
import CategoryStrip from '@/widgets/CategoryStrip';
import Hero from '@/widgets/Hero';
import Newsletter from '@/widgets/Newsletter';
import Container from '@/shared/ui/Container';
import Section from '@/shared/ui/Section';

export default function HomeView() {
  const dispatch = useAppDispatch();
  const { categories, status, categoriesStatus } = useAppSelector((state) => state.catalog);
  const featured = useAppSelector(selectFeaturedProducts);
  const newArrivals = useAppSelector(selectNewArrivals);

  useEffect(() => {
    if (status === 'idle') {
      dispatch(fetchProducts());
    }
    if (categoriesStatus === 'idle') {
      dispatch(fetchCategories());
    }
  }, [dispatch, status, categoriesStatus]);

  return (
    <>
      <Hero />
      <Benefits />
      <CategoryStrip categories={categories} />
      <Section>
        <Container>
          <div style={{ display: 'grid', gap: '0.75rem', marginBottom: '1.5rem' }}>
            <h2>Новые поступления</h2>
            <p>Свежие позиции для гостиной, dining zone и аккуратного повседневного хранения.</p>
          </div>
          <CatalogGrid products={newArrivals} loading={status === 'loading'} />
        </Container>
      </Section>
      <Section $soft>
        <Container>
          <div style={{ display: 'grid', gap: '0.75rem', marginBottom: '1.5rem' }}>
            <h2>Подборка редакции</h2>
            <p>Товары с лучшим рейтингом, которые хорошо показывают живой каталог проекта.</p>
          </div>
          <CatalogGrid products={featured.slice(0, 4)} loading={status === 'loading'} />
        </Container>
      </Section>
      <Newsletter />
    </>
  );
}
EOF

cat <<'EOF' > src/views/catalog/CatalogView.tsx
/** Design reminder: the catalog must balance business density with calm, premium discoverability. */
'use client';

import { useCallback, useEffect } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import styled from 'styled-components';
import { useAppDispatch, useAppSelector } from '@/app/store/hooks';
import { selectCatalogMeta, selectPaginatedProducts } from '@/app/store/selectors';
import { fetchCategories, fetchProducts, resetFilters, setCategory, setPage, setPerPage, setSearchQuery, setSort } from '@/app/store/slices/catalogSlice';
import { closeFilters, toggleFilters } from '@/app/store/slices/uiSlice';
import FiltersSidebar from '@/features/filters/ui/FiltersSidebar';
import SearchBar from '@/features/search-products/ui/SearchBar';
import SortSelect from '@/features/sort-products/ui/SortSelect';
import CatalogGrid from '@/widgets/CatalogGrid';
import Container from '@/shared/ui/Container';
import Pagination from '@/shared/ui/Pagination';
import EmptyState from '@/shared/ui/EmptyState';
import Button from '@/shared/ui/Button';
import { PAGE_SIZE_OPTIONS } from '@/shared/config/constants';

const Shell = styled(Container)`
  display: grid;
  gap: 1.5rem;
  padding-block: 2rem 4rem;
`;

const Header = styled.div`
  display: grid;
  gap: 0.85rem;
`;

const Layout = styled.div`
  display: grid;
  grid-template-columns: 300px minmax(0, 1fr);
  gap: 1.5rem;

  @media (max-width: 900px) {
    grid-template-columns: 1fr;
  }
`;

const Controls = styled.div`
  display: grid;
  gap: 1rem;
  grid-template-columns: 1.5fr 220px 160px auto;
  align-items: center;
  margin-bottom: 1.5rem;

  @media (max-width: 1100px) {
    grid-template-columns: 1fr 1fr;
  }

  @media (max-width: 720px) {
    grid-template-columns: 1fr;
  }
`;

const Select = styled.select`
  min-height: 52px;
  border-radius: ${({ theme }) => theme.radii.pill};
  border: 1px solid ${({ theme }) => theme.colors.border};
  background: rgba(255, 250, 244, 0.92);
  padding: 0 1rem;
`;

const Meta = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1rem;
  margin-block: 1rem 1.5rem;
`;

export default function CatalogView() {
  const dispatch = useAppDispatch();
  const pathname = usePathname();
  const router = useRouter();
  const searchParams = useSearchParams();
  const catalog = useAppSelector((state) => state.catalog);
  const ui = useAppSelector((state) => state.ui);
  const products = useAppSelector(selectPaginatedProducts);
  const meta = useAppSelector(selectCatalogMeta);

  useEffect(() => {
    if (catalog.status === 'idle') {
      dispatch(fetchProducts());
    }
    if (catalog.categoriesStatus === 'idle') {
      dispatch(fetchCategories());
    }
  }, [dispatch, catalog.status, catalog.categoriesStatus]);

  useEffect(() => {
    const query = searchParams.get('q') ?? '';
    const category = searchParams.get('category') ?? 'all';
    const sort = (searchParams.get('sort') as typeof catalog.filters.sort | null) ?? 'featured';
    const page = Number(searchParams.get('page') ?? '1');
    const perPage = Number(searchParams.get('perPage') ?? String(catalog.filters.perPage));

    if (query !== catalog.filters.query) dispatch(setSearchQuery(query));
    if (category !== catalog.filters.category) dispatch(setCategory(category));
    if (sort !== catalog.filters.sort) dispatch(setSort(sort));
    if (!Number.isNaN(page) && page !== catalog.filters.page) dispatch(setPage(page));
    if (!Number.isNaN(perPage) && perPage !== catalog.filters.perPage) dispatch(setPerPage(perPage));
  }, [dispatch, searchParams, catalog.filters]);

  useEffect(() => {
    if (catalog.filters.page > meta.totalPages) {
      dispatch(setPage(meta.totalPages));
    }
  }, [catalog.filters.page, meta.totalPages, dispatch]);

  const updateParams = useCallback(
    (patch: Record<string, string>) => {
      const params = new URLSearchParams(searchParams.toString());
      Object.entries(patch).forEach(([key, value]) => {
        if (!value || value === 'all' || (key === 'page' && value === '1')) {
          params.delete(key);
          return;
        }
        params.set(key, value);
      });
      router.replace(`${pathname}?${params.toString()}`);
    },
    [router, pathname, searchParams],
  );

  return (
    <Shell>
      <Header>
        <h1>Каталог</h1>
        <p>Поиск, фильтры, сортировка и пагинация собраны в один взрослый UX-поток.</p>
      </Header>
      <Layout>
        <FiltersSidebar
          categories={catalog.categories}
          activeCategory={catalog.filters.category}
          onSelectCategory={(category) => {
            dispatch(setCategory(category));
            dispatch(setPage(1));
            dispatch(closeFilters());
            updateParams({ category, page: '1' });
          }}
          onReset={() => {
            dispatch(resetFilters());
            dispatch(closeFilters());
            router.replace('/catalog');
          }}
          mobile
          open={ui.filtersOpen}
        />
        <div>
          <Controls>
            <SearchBar
              value={catalog.filters.query}
              onCommit={(value) => {
                dispatch(setSearchQuery(value));
                updateParams({ q: value, page: '1' });
              }}
            />
            <SortSelect
              value={catalog.filters.sort}
              onChange={(value) => {
                dispatch(setSort(value));
                updateParams({ sort: value, page: '1' });
              }}
            />
            <Select
              value={catalog.filters.perPage}
              onChange={(event) => {
                const value = Number(event.target.value);
                dispatch(setPerPage(value));
                updateParams({ perPage: String(value), page: '1' });
              }}
            >
              {PAGE_SIZE_OPTIONS.map((option) => (
                <option key={option} value={option}>{option} / стр.</option>
              ))}
            </Select>
            <Button $variant="secondary" onClick={() => dispatch(toggleFilters())}>Фильтры</Button>
          </Controls>
          <Meta>
            <span>Найдено товаров: {meta.total}</span>
            <span>Страница {meta.currentPage} из {meta.totalPages}</span>
          </Meta>
          {catalog.status === 'failed' ? (
            <EmptyState title="Не удалось загрузить каталог" description={catalog.error ?? 'Попробуй обновить страницу.'} href="/catalog" action="Обновить каталог" />
          ) : meta.total === 0 && catalog.status === 'succeeded' ? (
            <EmptyState title="Ничего не найдено" description="Сбрось фильтры или измени поисковый запрос, чтобы вернуть товары в подборку." href="/catalog" action="Сбросить поиск" />
          ) : (
            <>
              <CatalogGrid products={products} loading={catalog.status === 'loading'} />
              <div style={{ marginTop: '1.5rem' }}>
                <Pagination
                  currentPage={meta.currentPage}
                  totalPages={meta.totalPages}
                  onPageChange={(page) => {
                    dispatch(setPage(page));
                    updateParams({ page: String(page) });
                  }}
                />
              </div>
            </>
          )}
        </div>
      </Layout>
    </Shell>
  );
}
EOF

cat <<'EOF' > src/views/product/ProductDetailsView.tsx
/** Design reminder: the product page should feel immersive, spacious, and conversion-friendly. */
'use client';

import { useEffect } from 'react';
import styled from 'styled-components';
import { useAppDispatch, useAppSelector } from '@/app/store/hooks';
import { clearCurrentProduct, fetchProductById, fetchRelatedProducts } from '@/app/store/slices/productSlice';
import AddToCartButton from '@/features/add-to-cart/ui/AddToCartButton';
import WishlistToggleButton from '@/features/toggle-wishlist/ui/WishlistToggleButton';
import ProductGallery from '@/entities/product/ui/ProductGallery';
import ProductPrice from '@/entities/product/ui/ProductPrice';
import RelatedProducts from '@/widgets/RelatedProducts';
import Container from '@/shared/ui/Container';
import EmptyState from '@/shared/ui/EmptyState';
import Badge from '@/shared/ui/Badge';

const Shell = styled(Container)`
  display: grid;
  gap: 2rem;
  padding-block: 2rem 4rem;
`;

const Hero = styled.div`
  display: grid;
  grid-template-columns: 1.1fr 0.9fr;
  gap: 2rem;

  @media (max-width: 980px) {
    grid-template-columns: 1fr;
  }
`;

const Content = styled.div`
  display: grid;
  gap: 1.2rem;
  align-content: start;
`;

const Actions = styled.div`
  display: flex;
  gap: 1rem;
  align-items: center;
  flex-wrap: wrap;
`;

const InfoGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 1rem;
  margin-top: 1rem;
`;

const InfoCard = styled.div`
  padding: 1rem;
  border-radius: ${({ theme }) => theme.radii.md};
  background: rgba(255, 250, 244, 0.88);
  border: 1px solid ${({ theme }) => theme.colors.border};
`;

const Reviews = styled.div`
  display: grid;
  gap: 1rem;
`;

export default function ProductDetailsView({ id }: { id: number }) {
  const dispatch = useAppDispatch();
  const { current, related, status, relatedStatus, error } = useAppSelector((state) => state.product);

  useEffect(() => {
    dispatch(fetchProductById(id));
    return () => {
      dispatch(clearCurrentProduct());
    };
  }, [dispatch, id]);

  useEffect(() => {
    if (current) {
      dispatch(fetchRelatedProducts({ category: current.category, excludeId: current.id }));
    }
  }, [dispatch, current]);

  if (status === 'failed') {
    return <Container style={{ paddingBlock: '3rem' }}><EmptyState title="Товар не найден" description={error ?? 'Попробуй открыть карточку из каталога ещё раз.'} href="/catalog" action="Вернуться в каталог" /></Container>;
  }

  if (!current) {
    return <Container style={{ paddingBlock: '3rem' }}><p>Загружаем карточку товара...</p></Container>;
  }

  return (
    <Shell>
      <Hero>
        <ProductGallery images={current.images} title={current.title} />
        <Content>
          <Badge>{current.category.replace('-', ' ')}</Badge>
          <h1>{current.title}</h1>
          <p>{current.description}</p>
          <ProductPrice price={current.price} discountPercentage={current.discountPercentage} />
          <Actions>
            <AddToCartButton product={current} />
            <WishlistToggleButton productId={current.id} />
          </Actions>
          <InfoGrid>
            <InfoCard><strong>Рейтинг</strong><p>{current.rating} / 5</p></InfoCard>
            <InfoCard><strong>Наличие</strong><p>{current.availabilityStatus ?? `Stock: ${current.stock}`}</p></InfoCard>
            <InfoCard><strong>Доставка</strong><p>{current.shippingInformation ?? 'Доставка 3–7 дней'}</p></InfoCard>
            <InfoCard><strong>Гарантия</strong><p>{current.warrantyInformation ?? '1 year warranty'}</p></InfoCard>
          </InfoGrid>
        </Content>
      </Hero>
      <div style={{ display: 'grid', gap: '1rem' }}>
        <h2>Отзывы</h2>
        <Reviews>
          {(current.reviews ?? []).slice(0, 3).map((review) => (
            <InfoCard key={`${review.reviewerEmail}-${review.date}`}>
              <strong>{review.reviewerName}</strong>
              <p>{review.comment}</p>
              <span>Рейтинг: {review.rating}/5</span>
            </InfoCard>
          ))}
        </Reviews>
      </div>
      {relatedStatus !== 'failed' && related.length > 0 ? <RelatedProducts products={related} /> : null}
    </Shell>
  );
}
EOF

cat <<'EOF' > src/views/wishlist/WishlistView.tsx
/** Design reminder: wishlist should feel like a saved interior moodboard, not a dead utility page. */
'use client';

import { useEffect } from 'react';
import styled from 'styled-components';
import { useAppDispatch, useAppSelector } from '@/app/store/hooks';
import { selectWishlistProducts } from '@/app/store/selectors';
import { fetchProducts } from '@/app/store/slices/catalogSlice';
import CatalogGrid from '@/widgets/CatalogGrid';
import Container from '@/shared/ui/Container';
import EmptyState from '@/shared/ui/EmptyState';

const Shell = styled(Container)`
  display: grid;
  gap: 1.5rem;
  padding-block: 2rem 4rem;
`;

export default function WishlistView() {
  const dispatch = useAppDispatch();
  const { status } = useAppSelector((state) => state.catalog);
  const wishlistProducts = useAppSelector(selectWishlistProducts);

  useEffect(() => {
    if (status === 'idle') {
      dispatch(fetchProducts());
    }
  }, [dispatch, status]);

  return (
    <Shell>
      <div style={{ display: 'grid', gap: '0.75rem' }}>
        <h1>Wishlist</h1>
        <p>Локально сохранённые товары доступны из каталога и карточек товара.</p>
      </div>
      {wishlistProducts.length === 0 ? (
        <EmptyState title="Wishlist пока пуст" description="Сохрани несколько товаров из каталога, чтобы собрать свою подборку интерьера." href="/catalog" action="Перейти в каталог" />
      ) : (
        <CatalogGrid products={wishlistProducts} loading={status === 'loading'} />
      )}
    </Shell>
  );
}
EOF

cat <<'EOF' > src/views/cart/CartView.tsx
/** Design reminder: the cart page should translate stateful logic into a clean, trustworthy checkout prelude. */
'use client';

import Image from 'next/image';
import Link from 'next/link';
import styled from 'styled-components';
import { useAppDispatch, useAppSelector } from '@/app/store/hooks';
import { clearCart, removeFromCart } from '@/app/store/slices/cartSlice';
import QuantityControl from '@/features/change-quantity/ui/QuantityControl';
import { selectCartTotals } from '@/entities/cart/model/selectors';
import CartSummary from '@/widgets/CartSummary';
import Container from '@/shared/ui/Container';
import EmptyState from '@/shared/ui/EmptyState';
import { formatPrice } from '@/shared/lib/formatPrice';
import { routes } from '@/shared/config/routes';

const Shell = styled(Container)`
  display: grid;
  gap: 1.5rem;
  grid-template-columns: minmax(0, 1.2fr) 340px;
  padding-block: 2rem 4rem;

  @media (max-width: 980px) {
    grid-template-columns: 1fr;
  }
`;

const List = styled.div`
  display: grid;
  gap: 1rem;
`;

const Card = styled.article`
  display: grid;
  grid-template-columns: 140px 1fr auto;
  gap: 1rem;
  padding: 1rem;
  border-radius: ${({ theme }) => theme.radii.lg};
  background: rgba(255, 250, 244, 0.92);
  border: 1px solid ${({ theme }) => theme.colors.border};
  box-shadow: ${({ theme }) => theme.shadows.soft};

  @media (max-width: 720px) {
    grid-template-columns: 1fr;
  }
`;

const Visual = styled.div`
  position: relative;
  min-height: 140px;
  overflow: hidden;
  border-radius: ${({ theme }) => theme.radii.md};
`;

const RemoveButton = styled.button`
  border: none;
  background: transparent;
  color: ${({ theme }) => theme.colors.danger};
`;

export default function CartView() {
  const dispatch = useAppDispatch();
  const items = useAppSelector((state) => state.cart.items);
  const totals = useAppSelector(selectCartTotals);

  if (!items.length) {
    return (
      <Container style={{ paddingBlock: '3rem' }}>
        <EmptyState title="Корзина пуста" description="Добавь товары из каталога, чтобы протестировать reducers, selectors и persistence." href="/catalog" action="Перейти в каталог" />
      </Container>
    );
  }

  return (
    <Shell>
      <List>
        <div style={{ display: 'grid', gap: '0.75rem' }}>
          <h1>Корзина</h1>
          <p>Глобальное состояние корзины хранит позиции, quantity и derived totals.</p>
        </div>
        {items.map((item) => (
          <Card key={item.id}>
            <Link href={routes.product(item.id)}>
              <Visual>
                <Image src={item.thumbnail} alt={item.title} fill style={{ objectFit: 'cover' }} sizes="140px" />
              </Visual>
            </Link>
            <div style={{ display: 'grid', gap: '0.75rem' }}>
              <h3>{item.title}</h3>
              <p>{formatPrice(item.price)}</p>
              <QuantityControl productId={item.id} quantity={item.quantity} />
            </div>
            <div style={{ display: 'grid', gap: '0.75rem', justifyItems: 'end' }}>
              <strong>{formatPrice(item.price * item.quantity)}</strong>
              <RemoveButton onClick={() => dispatch(removeFromCart(item.id))}>Удалить</RemoveButton>
            </div>
          </Card>
        ))}
      </List>
      <CartSummary subtotal={totals.subtotal} delivery={totals.delivery} total={totals.total} onClear={() => dispatch(clearCart())} />
    </Shell>
  );
}
EOF

cat <<'EOF' > src/views/about/AboutView.tsx
/** Design reminder: the about page should deepen brand story through calm narrative and tactile imagery. */
'use client';

import Image from 'next/image';
import styled from 'styled-components';
import { STORY_IMAGE } from '@/shared/config/constants';
import Container from '@/shared/ui/Container';
import Section from '@/shared/ui/Section';
import Badge from '@/shared/ui/Badge';

const Hero = styled(Container)`
  display: grid;
  gap: 2rem;
  grid-template-columns: 1fr 1fr;
  align-items: center;

  @media (max-width: 960px) {
    grid-template-columns: 1fr;
  }
`;

const Visual = styled.div`
  position: relative;
  min-height: 520px;
  overflow: hidden;
  border-radius: ${({ theme }) => theme.radii.lg};
  box-shadow: ${({ theme }) => theme.shadows.lifted};
`;

const Facts = styled(Container)`
  display: grid;
  gap: 1rem;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
`;

const Fact = styled.article`
  padding: 1.5rem;
  border-radius: ${({ theme }) => theme.radii.lg};
  background: rgba(255, 250, 244, 0.92);
  border: 1px solid ${({ theme }) => theme.colors.border};
`;

export default function AboutView() {
  return (
    <>
      <Section>
        <Hero>
          <div style={{ display: 'grid', gap: '1rem' }}>
            <Badge>About the brand</Badge>
            <h1>Urban Nest родился как идея сделать спокойный дом новой нормой.</h1>
            <p>
              Внутри этого портфолио-проекта страница «О нас» показывает, что магазин — это не только каталог и API.
              Здесь есть контентная вёрстка, storytelling, статические маршруты и аккуратная композиция текста с изображением.
            </p>
            <p>
              Мы собираем мебель, декор и текстиль, которые помогают сделать пространство чище визуально и теплее
              эмоционально.
            </p>
          </div>
          <Visual>
            <Image src={STORY_IMAGE} alt="Brand story studio" fill style={{ objectFit: 'cover' }} sizes="(max-width: 960px) 100vw, 50vw" />
          </Visual>
        </Hero>
      </Section>
      <Section $soft>
        <Facts>
          <Fact><h3>Thoughtful curation</h3><p>Каждая подборка опирается на материал, масштаб и повседневный комфорт.</p></Fact>
          <Fact><h3>Frontend maturity</h3><p>Структура проекта показывает реальный route-level architecture вместо одного большого файла.</p></Fact>
          <Fact><h3>Human warmth</h3><p>Тёплая палитра и спокойный motion поддерживают ощущение домашнего пространства.</p></Fact>
        </Facts>
      </Section>
    </>
  );
}
EOF

cat <<'EOF' > src/views/contacts/ContactsView.tsx
/** Design reminder: the contacts page should turn basic forms into a calm branded interaction. */
'use client';

import { FormEvent, useState } from 'react';
import styled from 'styled-components';
import Button from '@/shared/ui/Button';
import Container from '@/shared/ui/Container';
import Input from '@/shared/ui/Input';
import Section from '@/shared/ui/Section';

const Grid = styled(Container)`
  display: grid;
  gap: 1.5rem;
  grid-template-columns: 0.9fr 1.1fr;

  @media (max-width: 920px) {
    grid-template-columns: 1fr;
  }
`;

const Card = styled.div`
  display: grid;
  gap: 1rem;
  padding: 1.5rem;
  border-radius: ${({ theme }) => theme.radii.lg};
  background: rgba(255, 250, 244, 0.92);
  border: 1px solid ${({ theme }) => theme.colors.border};
  box-shadow: ${({ theme }) => theme.shadows.soft};
`;

const Textarea = styled.textarea`
  min-height: 160px;
  border-radius: ${({ theme }) => theme.radii.md};
  border: 1px solid ${({ theme }) => theme.colors.border};
  background: rgba(255, 250, 244, 0.92);
  padding: 1rem;
`;

export default function ContactsView() {
  const [status, setStatus] = useState('');

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const formData = new FormData(event.currentTarget);
    const name = String(formData.get('name') ?? '').trim();
    const email = String(formData.get('email') ?? '').trim();
    const message = String(formData.get('message') ?? '').trim();

    if (!name || !email || !message || !email.includes('@')) {
      setStatus('Проверь имя, email и текст сообщения.');
      return;
    }

    setStatus('Сообщение отправлено в mock-flow. В реальном проекте сюда подключается backend или form service.');
    event.currentTarget.reset();
  };

  return (
    <Section>
      <Grid>
        <Card>
          <h1>Контакты</h1>
          <p>Эта страница показывает controlled form, базовую валидацию и контентный маршрут.</p>
          <p>Showroom: 18 Valencia Street, San Francisco</p>
          <p>Email: hello@urbannest.store</p>
          <p>Instagram: @urban.nest.store</p>
          <p>Карта здесь оставлена как стилизованная заглушка для будущей интеграции.</p>
        </Card>
        <Card as="form" onSubmit={handleSubmit}>
          <Input name="name" placeholder="Ваше имя" />
          <Input name="email" type="email" placeholder="Email" />
          <Textarea name="message" placeholder="Чем можем помочь?" />
          <Button type="submit">Отправить сообщение</Button>
          {status ? <p>{status}</p> : null}
        </Card>
      </Grid>
    </Section>
  );
}
EOF

cat <<'EOF' > src/app/layout.tsx
/** Design reminder: the root layout should maintain premium consistency across every route. */
import type { Metadata } from 'next';
import { Fraunces, Manrope } from 'next/font/google';
import Header from '@/widgets/Header';
import Footer from '@/widgets/Footer';
import StyledComponentsRegistry from './providers/StyledComponentsRegistry';
import { Providers } from './providers/Providers';
import './globals.css';

const fraunces = Fraunces({ subsets: ['latin', 'latin-ext'], variable: '--font-display' });
const manrope = Manrope({ subsets: ['latin', 'latin-ext'], variable: '--font-body' });

export const metadata: Metadata = {
  title: 'Urban Nest Store',
  description: 'Премиальный e-commerce проект на Next.js, TypeScript, styled-components и Redux Toolkit.',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ru" className={`${fraunces.variable} ${manrope.variable}`}>
      <body>
        <StyledComponentsRegistry>
          <Providers>
            <Header />
            {children}
            <Footer />
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
EOF

cat <<'EOF' > src/app/page.tsx
/** Design reminder: the landing route should open with atmosphere, clarity, and architectural confidence. */
import HomeView from '@/views/home/HomeView';

export default function HomePage() {
  return <HomeView />;
}
EOF

cat <<'EOF' > src/app/catalog/page.tsx
/** Design reminder: the catalog route should feel structured, calm, and fully merchandised. */
import type { Metadata } from 'next';
import CatalogView from '@/views/catalog/CatalogView';

export const metadata: Metadata = {
  title: 'Каталог | Urban Nest Store',
  description: 'Каталог товаров с фильтрами, поиском, сортировкой и пагинацией.',
};

export default function CatalogPage() {
  return <CatalogView />;
}
EOF

cat <<'EOF' > src/app/product/[id]/page.tsx
/** Design reminder: the dynamic product route should support storytelling, detail, and discovery. */
import type { Metadata } from 'next';
import ProductDetailsView from '@/views/product/ProductDetailsView';

export const metadata: Metadata = {
  title: 'Карточка товара | Urban Nest Store',
  description: 'Динамическая карточка товара с галереей, related products и add-to-cart flow.',
};

export default async function ProductPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  return <ProductDetailsView id={Number(id)} />;
}
EOF

cat <<'EOF' > src/app/wishlist/page.tsx
/** Design reminder: the wishlist route should feel saved, personal, and still commercial. */
import type { Metadata } from 'next';
import WishlistView from '@/views/wishlist/WishlistView';

export const metadata: Metadata = {
  title: 'Wishlist | Urban Nest Store',
  description: 'Избранные товары с локальным persistence и empty state.',
};

export default function WishlistPage() {
  return <WishlistView />;
}
EOF

cat <<'EOF' > src/app/cart/page.tsx
/** Design reminder: the cart route should translate reducers and selectors into a polished shopping flow. */
import type { Metadata } from 'next';
import CartView from '@/views/cart/CartView';

export const metadata: Metadata = {
  title: 'Корзина | Urban Nest Store',
  description: 'Корзина с quantity controls, totals и persisted state.',
};

export default function CartPage() {
  return <CartView />;
}
EOF

cat <<'EOF' > src/app/about/page.tsx
/** Design reminder: the about route should deepen the brand story without losing the product tone. */
import type { Metadata } from 'next';
import AboutView from '@/views/about/AboutView';

export const metadata: Metadata = {
  title: 'О нас | Urban Nest Store',
  description: 'История бренда, преимущества и контентная вёрстка Urban Nest Store.',
};

export default function AboutPage() {
  return <AboutView />;
}
EOF

cat <<'EOF' > src/app/contacts/page.tsx
/** Design reminder: the contacts route should keep the premium tone even in utility interactions. */
import type { Metadata } from 'next';
import ContactsView from '@/views/contacts/ContactsView';

export const metadata: Metadata = {
  title: 'Контакты | Urban Nest Store',
  description: 'Контакты, форма обратной связи и базовая валидация.',
};

export default function ContactsPage() {
  return <ContactsView />;
}
EOF

cat <<'EOF' > src/app/not-found.tsx
/** Design reminder: 404 should remain elegant and helpful, never abrupt or generic. */
import Container from '@/shared/ui/Container';
import EmptyState from '@/shared/ui/EmptyState';

export default function NotFound() {
  return (
    <Container style={{ paddingBlock: '3rem' }}>
      <EmptyState title="Страница не найдена" description="Похоже, маршрут не существует или был перемещён. Вернись в каталог и продолжи просмотр." href="/catalog" action="Открыть каталог" />
    </Container>
  );
}
EOF
